language: node_js
node_js:
- '8'
script:
- cd client
- npm run build
deploy:
  provider: gae
  keyfile: google-app-engine-client-secret
  project: react-linkedin-login
before_install:
- openssl aes-256-cbc -K $encrypted_9550f4951e06_key -iv $encrypted_9550f4951e06_iv
  -in app.yaml.enc -out app.yaml -d
- openssl aes-256-cbc -K $encrypted_9550f4951e06_key -iv $encrypted_9550f4951e06_iv
  -in google-app-engine-client-secret.json.enc -out google-app-engine-client-secret.json
  -d
